### ISSUE TITLE
DB 설계

### ISSUE THREAD

**Issue by HyeonJung** [skypotato/YOLO#1]

**Comment by skypotato** [comment]
User, Board, bucket list 등의 Table 필요...

**Comment by HyeonJung** [comment]
![](https://raw.githubusercontent.com/skypotato/YOLO/master/assets/erd.PNG)

**Comment by HyeonJung** [comment]
DB 생성 및 SQL문 작성

**Comment by HyeonJung** [comment]
![](https://github.com/HyeonJung/YOLO-DOC/blob/master/db/yolo-erd.PNG?raw=true)
