### ISSUE TITLE
화면 설계

### ISSUE THREAD

**Issue by HyeonJung** [skypotato/YOLO#2]

**Comment by skypotato** [comment]
Template 사용 (Wordpress 무료 Template 사용이 좋을 듯 - 반응형으로...)

**Comment by HyeonJung** [comment]
http://www.os-templates.com/free-website-templates/prestige

**Comment by HyeonJung** [comment]
- 회원 가입, 로그인 : @pizza301 
- 게시판 : 윤현중
- 마이페이지 : @skypotato

**Comment by skypotato** [comment]
@HyeonJung @pizza301 (추가) 기능 만들고 싶으면 만들어 보기

**Comment by HyeonJung** [comment]
- 글쓰기

![2](https://cloud.githubusercontent.com/assets/20272962/26343280/4636da40-3fd6-11e7-9874-01bb8fbe4914.PNG)

- 게시글 목록

![3](https://cloud.githubusercontent.com/assets/20272962/26343298/5bcb421a-3fd6-11e7-8a0a-1572443432de.PNG)


- 게시글 상세

![1](https://cloud.githubusercontent.com/assets/20272962/26343265/356ef224-3fd6-11e7-9a39-765aab6f09d0.PNG)

**Comment by skypotato** [comment]
- footer 없앤거
![image](https://cloud.githubusercontent.com/assets/22617513/26387713/a7eb5d56-408a-11e7-98c9-31de984d0842.png)
- 기존
![image](https://cloud.githubusercontent.com/assets/22617513/26387724/ba7e5130-408a-11e7-9778-92b96bfef40d.png)

**Comment by skypotato** [comment]
@HyeonJung @pizza301 footer 없는 게 낫지 않음?

**Comment by HyeonJung** [comment]
ㅇㅇ.. 기존 푸터 너무 난잡해보임 
저기 밑에 카피라이트 부분만 남기는게 괜찮을 것 같은데

**Comment by skypotato** [comment]
@HyeonJung @pizza301 관심 카테고리 관련 UI 만들기

**Comment by skypotato** [comment]
@pizza301 index 만들기
