### ISSUE TITLE
Use Case Diagram 작성

### ISSUE THREAD

**Issue by HyeonJung** [skypotato/YOLO#3]
@skypotato Use Case Diagram 작성

**Comment by skypotato** [comment]
@HyeonJung Start~~!!

**Comment by skypotato** [comment]
@HyeonJung @pizza301 수정할꺼 알려주삼 수정사항 없으면 이번주 모임 때 issue done처리함.

**Comment by HyeonJung** [comment]
@skypotato UML이 db폴더에 들어가있는데, uml폴더 만들어서 거기 안에다 수정 바람

**Comment by skypotato** [comment]
@HyeonJung 아라따

**Comment by skypotato** [comment]
@HyeonJung 무도 사진 땜시 confilct 났었네 언제 commit한거야 저건 ㅇㅅㅇ;;
